version: "3.5"

services:

  rest-nodejs:
    build: .
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "5m"
    container_name: rest-nodejs
    restart: on-failure
    ports:
      - "8080:8080"

